[package]
name = "localsetup"
version = "0.0.0"
edition = "2024"
description = "Setup your local computer / user automatically"
license = "GPL-3.0-only"

[dependencies]
toml = "0.9"
reqwest = {version = "0.12", features = ["blocking"]}
serde = {version = "1.0", features = ["derive"]}
