on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Create Release
        run: gh release create ${{ github.ref_name }} -t "Release ${{ github.ref_name }}" --generate-notes --draft
        env:
          GITHUB_TOKEN: ${{ github.token }}


  build:
    name: Build Linux Release
    runs-on: ubuntu-latest
    permissions: write-all
    needs: create-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ hashFiles('**/Cargo.lock') }}
      - name: Build binary
        run: cargo build --release
      - name: Copy binary
        run: cp target/release/localsetup .
      - name: Install minisign
        run: |
          sudo apt update
          sudo apt install minisign
      - name: Sign release
        run: echo | minisign -Sm localsetup -s <(echo "${MINISIGN_SECRET_KEY@E}")
        env:
          MINISIGN_SECRET_KEY: ${{ secrets.MINISIGN_SECRET_KEY }}
      - name: Upload binary
        run: gh release upload ${{ github.ref_name }} localsetup localsetup.minisig
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build-mac:
    name: Build Mac Release
    runs-on: macos-latest
    permissions: write-all
    needs: create-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ hashFiles('**/Cargo.lock') }}-mac
      - name: Build binary
        run: cargo build --release
      - name: Copy binary
        run: cp target/release/localsetup localsetup_mac
      - name: Install minisign
        run: |
          brew install minisign
      - name: Sign release
        run: echo "" | minisign -Sm localsetup_mac -s /dev/stdin <<< "$MINISIGN_SECRET_KEY"
        env:
          MINISIGN_SECRET_KEY: ${{ secrets.MINISIGN_SECRET_KEY }}
      - name: Upload binary
        run: gh release upload ${{ github.ref_name }} localsetup_mac localsetup_mac.minisig
        env:
          GITHUB_TOKEN: ${{ github.token }}
