on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build binary
        run: cargo build --release
      - name: Copy binary
        run: cp target/release/localsetup .
      - name: Install minisign
        run: |
          apt update
          apt install minisign
      - name: Sign release
        run: echo $MINISIGN_SECRET_KEY | minisign -Sm localsetup -s /dev/stdin
        env:
          MINISIGN_SECRET_KEY: ${{ secrets.MINISIGN_SECRET_KEY }}
      - name: Create Release
        run: gh release create ${{ github.ref_name }} -t "Release ${{ github.ref_name }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload binary
        run: gh release upload ${{ github.ref_name }} localsetup localsetup.minisig
        env:
          GITHUB_TOKEN: ${{ github.token }}
