on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ hashFiles('**/Cargo.lock') }}
      - name: Build binary
        run: cargo build --release
      - name: Copy binary
        run: cp target/release/localsetup .
      - name: Install minisign
        run: |
          sudo apt update
          sudo apt install minisign
      - name: Sign release
        run: echo | minisign -Sm localsetup -s <(echo "${MINISIGN_SECRET_KEY@E}")
        env:
          MINISIGN_SECRET_KEY: ${{ secrets.MINISIGN_SECRET_KEY }}
      - name: Create Release
        run: gh release create ${{ github.ref_name }} -t "Release ${{ github.ref_name }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload binary
        run: gh release upload ${{ github.ref_name }} localsetup localsetup.minisig
        env:
          GITHUB_TOKEN: ${{ github.token }}
